# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

# Modify the following configuration args to invoke your custom trainer, field, and so forth

global:
    exp_name: 'template_config'

optimizer:
    optimizer_type: 'rmsprop'
    lr: 0.001

dataset:
    dataset_type: 'multiview'
    multiview_dataset_format: 'standard'
    num_rays_sampled_per_img: 4096
    mip: 2
    bg_color: 'white'

renderer:
    tracer_type: 'PackedRFTracer'
    num_steps: 512  #512 in ngp_nerf, 16 in nglod
    raymarch_type: ray  # default is 'voxel' for all except ngp
    render_batch: 4000
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    shading_mode: 'rb'
    render_res:
        - 1024
        - 1024

# trainer:
#     trainer_type: 'TemplateTrainer'
#     epochs: 50
#     batch_size: 1
#     model_format: 'full'
#     valid_every: -1  # 50
#     save_every: -1   # 10
#     render_every: -1 # 10
trainer:
    trainer_type: 'MultiviewTrainer'
    epochs: 50
    batch_size: 1
    model_format: 'full'
    valid_every: 50
    save_every: 10
    render_every: 10

# Octree default:
# grid:
#     grid_type: 'OctreeGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 5
#     feature_std: 0.01
#     base_lod: 5
#     num_lods: 4
# HashGrid default:
grid:
    grid_type: 'HashGrid'
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 2
    feature_std: 0.01
    num_lods: 16
    tree_type: 'geometric'
    max_grid_res: 2048
    codebook_bitwidth: 19
# Triplanar default
# grid:
#     grid_type: 'TriplanarGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 4
#     feature_std: 0.01
#     base_lod: 5
#     num_lods: 4
# Codebook default
# grid:
#     grid_type: 'CodebookOctreeGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 5
#     feature_std: 0.01
#     base_lod: 5
#     num_lods: 4
#     codebook_bitwidth: 4
# Plenoxel HashGrid 1:
# grid:
#     grid_type: 'HashGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 28
#     feature_std: 0.01
#     num_lods: 4
#     tree_type: 'geometric'
#     max_grid_res: 2048
#     codebook_bitwidth: 19
# Plenoxel HashGrid 2:
# grid:
#     grid_type: 'HashGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 28
#     feature_std: 0.01
#     base_lod: 7  # 2
#     num_lods: 2
#     tree_type: 'quad'  # geometric
#     max_grid_res: 2048
#     codebook_bitwidth: 19
#Plenoxel Octree:
# grid:
#     grid_type: 'OctreeGrid'
#     interpolation_type: 'linear'
#     multiscale_type: 'sum'
#     feature_dim: 28
#     feature_std: 0.01
#     base_lod: 7  # 5
#     num_lods: 2  # 4

net:
    nef_type: 'MyPlenoxelNeuralField'
    hidden_dim: 128
    num_layers: 1
    out_dim: 4

embedder:
    embedder_type: 'positional'
